name: cs445
channels:
  - defaults
  - conda-forge
  - anaconda
  - nvidia
dependencies:
  - python
  - cudatoolkit
  - ipykernel
  - jupyterhub
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - opencv
  - pandas
  - scipy
  - tqdm
  - pip
  - pip:
      - tensorflow
      - keras
